name: Backup to Dropbox

on:
  push:
    branches:
      - '**'  # Run on all branches

jobs:
  backup_to_dropbox:
    uses: personal-workflows/backup-workflows/.github/workflows/backup.yml@main
    secrets:
      DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
